### ISSUE TITLE
Jenkins API now fails with JSON error

### ISSUE THREAD

**Issue by sschwartzee** [mchugh19/jenkins-saltapi#2]
After upgrading to Helium release of salt, salt-api builds now all fail with the following basic error code:

Problem: state.sls test.apitest to http://<saltserver>:8888 for BaseA:
net.sf.json.JSONException: JSONObject["return"] is not a JSONArray.

This happens regardless of success or failure of the actual salt call. I can authenticate successfully, and salt _does_ run, but it returns this error which kills the build job in Jenkins.

This would be potentially tolerable save that, in order to do a rolling restart, I run the same job to multiple different nodegroups, and since it fails on the first, never completes.

**Comment by mchugh19** [comment]
Eep, sorry for the response delay. Notifications were not configured properly for this repo and I missed this report. 

Not returning a json array should only happen when salt-api doesn't respond properly. Our environments are still not on 2014.7 due to other issues, so I'll set up a new 2014.7 test and see what has changed.

**Comment by sschwartzee** [comment]
Cool! Please let me know, as at the moment it's breaking production. :(

On Thu, Jan 1, 2015 at 11:36 AM, mchugh19 notifications@github.com wrote:

> Eep, sorry for the response delay. Notifications were not configured
> properly for this repo and I missed this report.
> 
> Not returning a json array should only happen when salt-api doesn't
> respond properly. Our environments are still not on 2014.7 due to other
> issues, so I'll set up a new 2014.7 test and see what has changed.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mchugh19/jenkins-saltapi/issues/2#issuecomment-68495765
> .

## 

Steven Schwartz | Engineering Team
Education Elements, Inc.
steven.schwartz@edelements.com | (510) 289-4275

**Comment by mchugh19** [comment]
I've just released a new point release (1.4.2) that corrects the problems I've found. 

You will still need to specify the runner permission for the user defined by jenkins, and then restart both the salt-master and your salt-api. 

external_auth:
  pam:
    jenkins:
      - '@runner'
      - .*

If you continue to experience any problems, please let me know and send the entirety of the jenkins output.

**Comment by mchugh19** [comment]
Seems to be good with current salt release. Please reopen if there are any issues.
