### ISSUE TITLE
Can't pass arguments that contain equals sign in cmd.run

### ISSUE THREAD

**Issue by devshorts** [mchugh19/jenkins-saltapi#3]
If I have an option to pass to a command argument the kwargs parser pulls out the `=` sign in my arguments and parses it instead as a dictionary argument.

For example

`/usr/sbin/cmd --foo=bar`

Can't be run

**Comment by mchugh19** [comment]
Ick, that's not great. I'll cut a new release soon that separates args from
salt's kwargs to clean this up.

**Comment by devshorts** [comment]
Awesome! Thanks

**Comment by mchugh19** [comment]
Kicked off a beta where the kwargs entries have been explicitly split out from args. Please test and let me know if this resolves your issues.

https://github.com/mchugh19/jenkins-saltapi/releases/download/v1.5-beta/saltstack.hpi

**Comment by devshorts** [comment]
Awesome. I'll give it a shot next week

**Comment by devshorts** [comment]
@mchugh19 :+1: working as expected :)

**Comment by mchugh19** [comment]
I've just pushed this out as version 1.5. You should see it in jenkins within the next 24 hours.
