### ISSUE TITLE
Question: Is there a way to specify batch-size.

### ISSUE THREAD

**Issue by zerthimon** [mchugh19/jenkins-saltapi#4]
From the salt man page:
`
-b BATCH, --batch-size=BATCH
              Instead of executing on all targeted minions at once, execute on a progressive set of minions. This option takes an argument in the form of an explicit number of  minions  to  execute  at
              once, or a percentage of minions to execute on.
`
Is this possible at all with salt-api ?

**Comment by mchugh19** [comment]
It sure is! Just select the local_batch client interface. That will give you a batch size text box.

**Comment by zerthimon** [comment]
@mchugh19 Thanks a lot, it's really awesome that I can specify the batch size.
It works wll when I define batch size, however, when I tried using a variable {{BATCH_SIZE}} the job failed:
`13:38:08 Running in batch mode. Batch size: {{BATCH_SIZE}}` seems like the variable is not expanding.
I'm setting the variable earlier in the job's env groovy script (it's determined by enviroment: 100% for staging and 1 for production):

```
if (ENVIRONMENT == 'production') {
    map['BATCH_SIZE'] = '1'
} else {
    map['BATCH_SIZE'] = '100%'
}
```

Any ideas ?

Edit: typos

**Comment by mchugh19** [comment]
Oh gocha! You are correct, that field isn't being expanded. That's a pretty simple fix, so I'll get that out soon.

**Comment by zerthimon** [comment]
That's awesome!
Thanks!

**Comment by mchugh19** [comment]
This was recently added to the master branch. Will be in the next release.
