### ISSUE TITLE
Usage example with Jenkinsfile

### ISSUE THREAD

**Issue by fracklen** [mchugh19/jenkins-saltapi#5]
Hey! Awesome idea to let jenkins integrate to the salt master!

Is it currently possible to use Jenkins credentials and call the salt-api from a stage in the Jenkinsfile for a build pipeline? I'm guessing this would be great to have in the docs. 

If you would point me in the right direction, I would be happy to document it :)

**Comment by mchugh19** [comment]
Yep yep! Not yet released, but pipeline functionality was just added to master. See jenkinsci/saltstack-plugin#33
